# Configuración del Nodo 1 (ID=0)
nodo.id=0
nodo.puerto=5001
nodo.puerto.nodos=5101
nodo.total=3
# Peers: host:puerto de los otros nodos (para clientes)
# El puerto inter-nodo se calcula como puerto + 100

nodo.peers=100.82.103.13:5002,100.120.9.53:5003
