
# Configuración del Nodo 3 (ID=2)
nodo.id=2
nodo.puerto=5003
nodo.puerto.nodos=5103
nodo.total=3
# Conectarse al Nodo 1 (5001) y Nodo 2 (5002) que están en el PC Local
nodo.peers=100.82.103.13:5001,100.82.103.13:5002

# Configuración para conectarse a la Base de Datos del PC Local
db.host=100.82.103.13
db.user=root
db.password=
